'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Web
Imports System.Web.Profile


Public Class ProfileCommon
    Inherits System.Web.Profile.ProfileBase

    
    Public Overridable Property ProfileVersion() As Integer
        Get
            Return CType(Me.GetPropertyValue("ProfileVersion"), Integer)
        End Get
        Set(ByVal value As Integer)
            Me.SetPropertyValue("ProfileVersion", value)
        End Set
    End Property

    
    Public Overridable Property FirstName() As String
        Get
            Return CType(Me.GetPropertyValue("FirstName"), String)
        End Get
        Set(ByVal value As String)
            Me.SetPropertyValue("FirstName", value)
        End Set
    End Property

    
    Public Overridable Property LastName() As String
        Get
            Return CType(Me.GetPropertyValue("LastName"), String)
        End Get
        Set(ByVal value As String)
            Me.SetPropertyValue("LastName", value)
        End Set
    End Property

    Public Overridable Function GetProfile(ByVal username As String) As ProfileCommon
        Return CType(ProfileBase.Create(username), ProfileCommon)
    End Function
End Class
